version: 1
subject: "New Relic Roundtrip Mail"
debug: false
proxy:
  host:
  port:
  auth:
    username:
    password:
newrelic:
  accountId:
  insertKey:
scenarios:
  - from: ""
    to: ""
    smtp_host: ""
    smtp_port:
    smtp_user: ""
    smtp_password: ""
    protocol: "imap"
    protocol_host: ""
    protocol_port:
    protocol_user: ""
    protocol_password: ""
    protocol_tls: false
    folder: "INBOX"
  - from: ""
    to: ""
    smtp_host: ""
    smtp_port: ""
    smtp_user: ""
    smtp_password: ""
    protocol: ""
    protocol_host: ""
    protocol_port:
    protocol_user: ""
    protocol_password: ""
    protocol_tls: false
